### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by weijia-cheng** [PopcornPlease/charles-w-chesnutt_the-marrow-of-tradition#1]
# Typography

- [x] `chapter-12`: You have a miscurled `you‘`. (Flagged by lint. Meta note, it’s good practice to run lint before submitting for review to catch things like this.)

# Spelling

- [x] Running `modernize-spelling` removes the space before many instances of `’ll`; I’m inclined to accept most of these changes apart from `w’at ’ll` and `gin’l ’ll` which already have contractions.
- [x] `chapter-32`: `common-sense` was changed to `commonsense` by modernize-spelling, which needs to be reverted because this spelling is for the adjective and not the noun. Modernize-spelling will flag these ambiguous modernizations and these should be manually reviewed after you run that tool.
- [x] `chapter-24`: `se find-mismatched-dashes` flags that you have both `ter-night` and `ternight` in your text. It looks like `ter-night` is the more prevalent form and the `ternight` in chapter-24 might have been a mistranscription. You can change it to `ter-night` (no editorial tag because it does match the scans).
- [x] `z3998:poem` should be replaced with `z3998:verse` for your verse quotes, because I believe none of them are quoting the entire poem. `z3998:verse` is for fragments, and `z3998:poem` is for entire poems.

# Semantics

- [x] `chapter-10`: Remove the italics around `amour propre`; we don’t put italics around words found in Merriam-Webster. Also, it would have be `xml:lang="fr"` for French, not `la` for Latin ;)
- [x] Ditto for the italics around `sine qua non`, `auto-da-fé`, `confrères`, etc. Leave `meum` and `tuum` though; the only hit in M-W is `meum et tuum` which is not the same thing.
- [x] `chapter-28`: You have an `<em>` around `impasse` but the italics from the original text were probably because it was being treated as a foreign-language word at the time. In cases like this we remove the italics altogether. `mésalliance` has a similar problem.
- [x] `To the Editor of the Everyday Book` in the epigraph seems to be the title of a poem ([ref](https://books.google.com/books?id=gTGTvgEACAAJ&pg=PA63#v=onepage&q&f=false)). Hence it should go into quotation marks, and not be in italics. In a editorial commit I would change this to `Charles Lamb, “To the Editor of the Everyday Book”`.
- [x] `chapter-16`: `was` is still in an `i` and not in an `em`. I see some `i` tags elsewhere that need to be addressed. Use the `grep --recursive --line-number "<i>" src/epub/text/*.xhtml` command to help find these issues. You can check all of your usages of italics with `grep --recursive --line-number --extended-regexp "<i|<em" src/epub/text/*.xhtml`.

# Code Style

- [x] Run `se clean`; it seems there are some whitespace issues. In general it is good practice to run clean before submitting for review.
- [x] Something I have never seen before: `se build-title` is changing some invisible character at the end of your halftitlepage. When I run hexdump before and after `se build-title` I see that the last few bytes, `003e`, are changed to `0a3e`. `U+000A` is the line feed in Unicode, and my interpretation of what is happening is that you were missing the line feed at the end of your halftitlepage and build-title, for some reason, is adding it back in for you. You might want to check what your editor settings are, especially if you are on Windows since I believe Windows has different line termination encoding from Linux.
- [x] Rerun `se build-toc`. You get a different table of contents with and without a halftitlepage (I have run into this many times myself when I forget to add a halftitlepage the first time around).
- [x] `se build-images` changes the source image—I am not entirely sure what this is doing but we should accept the change.

# Colophon

- [x] `https://jacobzaengle.com` doesn’t link anywhere for me? I can’t connect.

# Metadata

- [x] Short description should probably more succinct. Also, Civil War should be capitalized.
- [x] I don’t think “reconstructionist South” is very idiomatic? “The South during Reconstruction” would be more like I am used to.
- [x] The `nacoaf` field should be `http://id.loc.gov/authorities/names/n79138741` (I just stole this from the other Chesnutt ebook, *The Conjure Woman*.)
- [x] Assuming you fix the url for your website, you can add it as your homepage in the metadata (`<meta property="se:url.homepage" refines="#transcriber-1"`)

# Commit History

These changes will require doing a rebase with git (`git rebase -i`) to update the commit history. People come to SE with a wide range of levels of experience with git. If you need a detailed explanation for any or all of these steps, I will happily provide that.

- [x] The second commit (“Removed Gitenberg cruft”) needs to be squashed into the initial commit. We specifically should not have anything with the Gutenberg license in our commit history.
- [x] e1d386bef4e749ceb477e6083145b9e8ba97f3d7: This needs to be tagged as `[Editorial]` since it is changing spelling away from the printed text.
- [x] e8515737e57c35b2af05368917e45634e78dcca9: This is *not* an editorial commit, because you are simply restoring the originally printed text. As a rule, changing PG *to* match the scans is not editorial, but changing text *away* from the scans to fit SE standards *is* editorial. Similar issue with 8c7ba461d0d5448acecf91583a941a2291266eac.
- [x] I would suggest going through your commit history and renaming any commits that don’t have names that accurately describe what is going on in the change. There are a couple of commits where I think you accidentally commited changes that were meant to go into something else, which is leading to confusing commit messages.

# Meta

More suggestions on how to approach future projects than things to fix.

- You had a commit to run both clean and add an epigraph; in the future those would be better as distinct commits (one to run clean and another to add the epigraph). It’s easier to review commits when they only have one sort of change.
- It is easier to review your code, for your first commits at least, if you follow the commit scheme suggested in the production guide (including the commit messages) as closely as possible. The reviewer has to go through your commit history and inspect (if only at an eyeball level) what is going into each commit, so anything to save some time for is appreciated :)
- Your “Correct improper single quotes with appropriate elision” seems to have mixed in some irrelevant changes to the epigraph. I think you meant for that change to go into the following manual typography commit? In this case, it’s not a big deal, but in the future we want to be careful as we create commits so that we don’t accidentally mix editorial and non-editorial changes into the same commit. SE has an unusual level of emphasis on commit hygiene in this regard, compared to everywhere I’ve worked professionally!

**Comment by PopcornPlease** [comment]
This review is so beautifully formatted! I already expressed my gratitude in a previous post, but I really do appreciate you providing such a thorough and kind review.

**Comment by weijia-cheng** [comment]
You're welcome! I've been doing this for a while now so I've had plenty of practice spotting things and providing feedback :)

**Comment by PopcornPlease** [comment]
Well, the feedback was constructive, and though I have had some experience with Git, it has been some time since I last was actively doing work, which I am going to be using as my excuse for all my poor Git hygiene. I look forward to carrying all the feedback and kindness you have shared with me into future projects!

I believe I addressed most of the changes! The only one I still need to go through is correcting my commit history, which I am realizing now is quite embarrassingly bad. I'll be working on that this evening.

**Comment by PopcornPlease** [comment]
Hey Weijia, I believe I corrected all the issues that were in my original work. When you have the time, I'd appreciate you giving this work another review.

**Comment by weijia-cheng** [comment]
Looks much better! There are a handful of issues remaining:

# Typogrify

- [x] Run `typogrify` and accept the change. There is a missing word joiner before an em-dash in chapter-31.

# Semantics

- [x] I still see an instance of `noblesse oblige` in an `<em>` in chapter-7.
- [x] You don’t need both `i1` and `i2` in the chapter-28 verse. The indent classes are only meaningful relative to the baseline (no indentation). If the lowest level of indentation is `i1`, that means `i2` is effectively acting as `i1`. What we should do is remove the `i1` and change to `i2` (don’t forget to delete the now-superfluous `i2` rule from the CSS).
- [x] Since you are no longer using a link to a personal site in the colophon, you should wrap your name with `<b epub:type="z3998:personal-name">`.

# Metadata

- [x] Capitalize “Reconstruction” in the short description.
- [x] The last sentence of the first paragraph of the long description is a bit unwieldy because you describe him as “working” at two different points in the sentence. I think you can find a more elegant way to word this.


# Commit History

- [x] 942a54e064ee3904c58a38592988c1402dcf390d is non-editorial.

Looking forward to seeing this get done! Now might be as good of a time as any to mention that I was the one who originally put this on the wanted works list. I was feeling then that having the first producers list be mostly 20s pulp fiction wasn't necessarily going to make the best first impression on everyone (it certainly didn't on me the first time I started contributing to SE!), hence I added *Marrow* :)

**Comment by PopcornPlease** [comment]
I appreciate you putting this work on the list. Like most areas, there is a deep and necessary need for the presence of diverse voices. If there are any other works, or list of works, that you feel would help make SE a more dynamic place, please let me know! 

Also, outside of developing a healthy connection to the SE Manual of Style, are there other works or areas of learning that could help me become a better volunteer/contributor?

**Comment by weijia-cheng** [comment]
The changes look very good, there is only one minor thing left I found, then I can send this over to Alex for final review and publishing.

- [x] `i2` rule still has to be removed from `local.css`.

As for advice, I would suggest that, if your goal is to eventually produce *The Varieties of Religious Experience* (which I am looking forward to by the way! not a book I would read a second time for fun but it definitely had an influence on me the first time around) it would be helpful to familiarize yourself with how some other complicated nonfiction texts have been produced in the past.

From productions I've worked on myself, [*What Is Art?*](https://github.com/standardebooks/leo-tolstoy_what-is-art_aylmer-maude) and [*What Is Property?*](https://github.com/standardebooks/pierre-joseph-proudhon_what-is-property_benjamin-tucker) have turned out to have very complex formatting and structuring. *What Is Art?* is especially complex in the way it incorporates extended verse quotations into the text. I haven't looked at the code for this one at all but I would also look at the [discussion thread and source code for *Principia Ethica*](https://groups.google.com/g/standardebooks/c/cYqfCz0ujh4/m/t2yQSrMNAQAJ); it's a great example of collaboration between the producer, manager, and reviewer on a complex nonfiction book, especially Erin's final notes.

**Comment by PopcornPlease** [comment]
I've read your production of _What Is Art_! I'll check out the repo and look through the commit history of it. I also saw that SE recently published _Principia Ethica_ and looking at the discussion thread is such a good suggestion. Thank you, Weijia!
